# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: serverlessfg
# "service" is the name of this project. This will also be added to your AWS resource names.
service: python-image-thumbnail

provider:
  name: aws
  runtime: python3.12
  region: eu-west-1
  # profile: fgbaiye
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    THUMBNAIL_SIZE: 128
    REGION_NAME: ${self:provider.region}
    DYNAMODB_TABLE: ${self:custom.dynamoTable}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action: "*"
        - Effect: "Allow"
          Action: 
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    

custom:
  bucket: fgbaiye-demo-thumbnails
  dynamoTable: img-url-table
  pythonRequirements:
    dockerizePip: true 

functions:
  s3_thumbnail_generator:
    handler: handler.s3_thumbnail_generator
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
    layers:
      - arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-p312-Pillow:4


  list_thumbnails:
    handler: handler.s3_get_thumbnail_urls
    events:
      - http:
          path: images/all
          method: get
          cors: true
    layers:
      - arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-p312-Pillow:4

  get_thumbnail:
    handler: handler.s3_get_thumbnail
    events:
      - http:
          path: images/get/{id}
          method: get
          cors: true
    layers:
      - arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-p312-Pillow:4

  delete_thumbnail:
    handler: handler.s3_delete_thumbnail
    events:
      - http:
          path: images/delete/{id}
          method: delete
          cors: true
    layers:
      - arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-p312-Pillow:4

resources:
  Resources:
    ImagesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}


plugins:
  - serverless-python-requirements
